\def \VLJ   {V_{\rm LJ}}
\def \VRLJ  {V_{\rm RLJ}}
\def \sigA  {\sigma_{\rm A}}
\def \epsA  {\epsilon_{\rm A}}
\def \sigw  {\sigma_{\rm w}}
\def \epsw  {\epsilon_{\rm w}}
\def \mhat {\hat{\bm m}}
\def \RRij {{\bm R}_{\rm ij}}
\def \RRijm {{\bm R}_{\rm ij-1}}
\def \Es    {E_{\rm s}}
\def \Eb    {E_{\rm bend}}
\def \Ebl   {E_{\rm bulk}}
\def \BR    {B_{\rm R}}
\def \YR    {Y_{\rm R}}
\def \etau  {\eta_{\rm u}}
\def \ET    {\mbox{ET}}
\def \lel   {\ell_{\rm el}}
\def \lth   {\ell_{\rm th}}
\def \Yt    {Y_{\rm 3d}}
\def \sigmat {\sigma_{\rm 3d}}
\def \Eabmn {E_{\alpha\beta\mu\nu}}
\def \Eijkl {E_{ijkl}}
\def \Sigab {\sigma_{\alpha\beta}}
\def \umn   {u_{\mu\nu}}
\def \uab   {u_{\alpha\beta}}
\def \Um    {U_{\mu}}
\def \Un    {U_{\nu}}
\def \delm  {\partial_{\mu}}
\def \deln  {\partial_{\nu}}
\def \deli  {\partial_{i}}
\def \delj  {\partial_{j}}
\def \delij {\partial_{ij}}
\def \anot   {a_{\rm 0}}
\def \qq     {\bm{q}}
\def \hq     {\hat{h}}
\def \xj     {x_{\rm j}}
\def \yj     {y_{\rm j}}
\def \mHthr  {\mathcal{H}_{\rm thr}}
\def \rb     {r_{\rm block}}
\def \sigman {\sigma_{\rm 0}}
\def \alphan {\alpha_{\rm 0}}
\newcommand*\dif{\mathop{}\!\mathrm{d}}
\newcommand{\ma}[1]{\ensuremath{\mathbb{#1}}}
\def \Jdif {J_{\rm dif}}
\def \Jad {J_{\rm ad}}
\def \Ldot {\dot{L}}
\def \JJ {\bm{J}}
\def \mE {\mathcal{E}}
\def \kL {k_{\rm L}}
\def \aa {a}
\def \mU {\mathcal{U}}
\def \mL   {\mathcal{L}}
\def \Phiz {\Phi_{\rm 0}}
\def \mF {\mathcal{F}}
\def \zhat {\hat{z}}
\def \phih {\hat{\phi}}
\def \rz  {r_{\rm 0}}
\def \kphi  {k_{ \phi}}
\def \Lphi  {L_{\phi}}
\def \Lphiv  {L^{\parallel}_{\phi}}
\def \Lphih  {L^{\perp}_{\phi}}
\def \Sphi  {S_{\phi}}
\def \Vta {V^{\alpha}_{\rm 2}}
\def \Voa {V^{\alpha}_{\rm 1}}
\def \VVt {\bm{V}_{2}}
\def \vvt {\bm{v}_{2}}
\def \taul {\tau_{\ell}}
\def \dtwo {d_{\rm 2}}
\def \Dtwo {D_{2}}
\def \muc {\mu_{\rm c}}
\def \zast {z^{\ast}}
\def \AA {\mathcal{A}}
\def \Ku {{\rm Ku}}
\def \Pphi {P_{\phi}}
\def \PE {P^{\rm E}}
\def \PL {P^{\rm L}}
\def \PI {P^{\rm I}}
\def \QE {Q^{\rm E}}
\def \QL {Q^{\rm L}}
\def \QI {Q^{\rm I}}
\def \mC {\mathcal{C}_{\Lambda}}
\def \mP {\mathcal{P}}
\def \vrho {\varrho}
\def \mQ {\mathcal{Q}}
\def \urt {{\bm u}({\bm r},t)}
\def \ap {R_{\rm p}}
\def \sigmax {\sigma_{\rm max}}
\def \NC {N_{\rm c}}
\def \NCST {N_{\rm c}^{\rm ST}}
\def \an {a_{n}}
\def \at {a_{t}}
\def \TA {T_{\rm A}}
\def \TB {T_{\rm B}}
\def \TC {T_{\rm C}}
\def \TD {T_{\rm D}}
\def \TV {T_{\rm vortical}}
\def \TS {T_{\rm strain}}
\def \rhof {\rho_{\rm f}}
\def \rhop {\rho_{\rm p}}
\def \bfu {{\bf u}}
\def \mzero {m_{\rm 0}}
\def \uu  {{\bm u}}
\def \UU  {{\bm U}}
\def \kk  {{\bm k}}
\def \vv  {{\bm v}}
\def \ff  {{\bm f}}
\def \oo  {{\bm \omega}}
\def \ueta {u_{\rm \eta}}
\def \teta {\tau_{\rm \eta}}
\def  \xx  {{\bm x}}
\def  \XX  {{\bm X}}
\def \Xdot {\dot{{\bm X}}}
\def \xdot {\dot{{\bm x}}}
\def \vdot {\dot{{\bm v}}}
\def  \VV  {{\bm V}}
\def  \Vi  {V_{i}}
\def  \Va  {V_{\alpha}}
\def  \Vb  {V_{\beta}}
\def  \Rb  {R_{\beta}}
\def  \vi  {v_{i}}
\def  \ua  {u_{\alpha}}
\def  \uao  {u_{\alpha}^{\rm (1)}}
\def  \uat  {u_{\alpha}^{\rm (2)}}
\def  \ub  {u_{\beta}}
\def  \va  {v_{\alpha}}
\def  \vb  {v_{\beta}}
\def  \vao  {v_{\alpha}^{\rm (1)}}
\def  \vat  {v_{\alpha}^{\rm (2)}}
\def  \ux  {u_{\rm x}}
\def \lzij  {\ell^{\rm 0}_{\rm ij}}
\def  \Rij  {R_{\rm ij}}
\def  \Rijm  {R_{\rm ij-1}}
\def  \Ri  {\bm{R}_{\rm i}}
\def  \Rj  {\bm{R}_{\rm j}}
\def \Vdot {\dot{{\bm V}}}
\def \p {p}
\def \cs {c_{\rm s}}
\def \Lx {L_x}
\def \Ly {L_y}
\def \Lz {L_z}
\def \zz {{\bm z}}
\def \Rhat {\hat{R}}
\def  \RR  {{\bm R}}
\def  \KK  {{\bm K}}
\def  \Vc  {V_{\rm c}}
\def  \Rc  {R_{\rm c}}
\def  \VR  {V_{R}}
\def  \VRa  {|V_{R}|}
\def  \VRn  {V_{\rm n}}
\def   \zR {z_{R}}
\def   \zstar {z^\ast}
\def   \tstar {t^\ast}
\def  \VRc  {V^c_R}
\def \kinj {k_{\rm inj}}
\def \linj {\ell_{\rm inj}}
\def \taus {\tau_{\rm s}}
%\def \taup {\tau_{\rm p}}
\def \taup {\tau}
\def \tauf {\tau_{\rm f}}
\def \ld {\ell_{\rm d}}
\def \bomega {{\bm \omega}}
\def \vl {{\bm v}(t|t_0,{\bm r}_0)}
\def \uirz {u_i({\bm r},0)}
\def \ujrt {u_j({\bm r},t)}
\def \vliz {v_i(0|t_0,{\bm r}_0)}
\def \vljt {v_j(t|t_0,{\bm r}_0)}
\def \u {{\bm u}}
\def \fxt {{\bm f}({\bm x},t)}
\def \xhat {\hat{x}}
\def \yhat {\hat{y}}
\def \f {{\bm f}}
\def \grad {{\bm \nabla}}
\def \curl {{\bm \nabla} \times}
\def \dive {{\bm \nabla}\cdot}
\def \lap {\nabla^2}
\def \delt {\partial_t}
\def \Dt {D_t}
\newcommand{\bra}[1]{\left\langle #1\right\rangle}
\def \Ch {\mbox{Ch}}
\def \La {\mbox{La}}
\def \Fl {\mbox{Fl}}
\def \Bo {\mbox{Bo}}
\def \Sc {\mbox{Sc}}
\def \Ga {\mbox{Ga}}
\def \Ar {\mbox{Ar}}
\def \At  {\mbox{At}}
\def \Rey  {\mbox{Re}}
\def \Fv  {\mbox{FvK}}
\def \Rel  {\mbox{Re}_\lambda}
\def \Ma  {\mbox{Ma}}
\def \ao  {a_1}
\def \at  {a_2}
\def \St  {\mbox{St}}
\def \Fr  {\mbox{Fr}}
\def \Sto  {\mbox{St}_{\rm 1}}
\def \Stt  {\mbox{St}_{\rm 2}}
%\def \Stm  {\overline{\mbox{St}}}
\def \Stm  {{\mbox{St}}_{\rm M}}
\def \StL  {{\mbox{St}}_{\rm L}}
\def \Tl  {T_{\rm L}}
\def \Ttran  {T_{\rm tran}}
\def \Teddy {T_{\rm eddy}}
\def \TLD {T^{\rm D}_{\rm L}}
\def \TED  {T^{\rm D}_{\rm E}}
\def \Tinj {T_{\rm inj}}
\def \Teta {T_{\eta}}
\def \tper {\mathrm{t_{pers}}}
\def \trms {\tau_{\rm rms}}
\def \tp {\tau^{\prime}}
\def \Tmean {T^+_{\rm mean}}
\def \tres  {\tau}
\def \kf  {k_{\rm f}}
\def \kone  {k_{\rm 1}}
\def \urms  {u_{\rm rms}}
\def \vrms  {v_{\rm rms}}
\def \orms  {\omega_{\rm rms}}
\def \Vrms {V^{\rm rms}_{\rm R}}
\def \vsling {v_{\rm sling}}
\def \vejected {v_{\rm ejected}}
\def \Np  {N_{\rm p}}
\def \Nd  {N_{\rm d}}
\def \pp  {P^+}
\def \pn  {P^-}
\def \mQp {{\mathcal Q}^{+}}
\def \Qp {Q^{+}}
\def \ppe  {P^+_{\rm E}}
\def \ppl  {P^+_{\rm L}}
\def \ppq  {P^+_{\rm Q}}
\def \pne  {P^-_{\rm E}}
\def \pnl  {P^-_{\rm L}}
\def \pnq  {P^-_{\rm Q}}
\def \qnl  {Q^-_{\rm L}}
\def \qnq  {Q^-_{\rm Q}}
\def \intT  {T_{\rm integral}}
\def \tu {T_{\rm u}}
\def \dl {\ell}
\def \dvl {\delta v(\ell)}
\def \NI {N_{\rm I}}
\def \nI {n_{\rm I}}
\def \zetap {\zeta_{\rm p}}
\def\T{{\mathbb T}}
\def\subs#1#2{\mbox{\small${#1\atop#2}$}}
\def\nL{\nabla^{\rm L}}
\def\rf#1{(\ref{#1})}
\def\i{{\rm i}}
\def\e{{\rm e}}
\def\d{{\rm d}}
\def\D{{\rm D}}
\def\bu{\mathbf{u}}
\def\bx{{\bm x}}
\def\by{{\bm y}}
\def\bxi{{\bm\xi}}
\def\ba{{\bm a}}
\def\bk{{\bm k}}
\def\bom{{\bm\omega}}
\def\oz{{\bm\omega}^{\rm(init)}}
\def\vz{{\bm v}^{\rm(init)}}
\def\tf{t_{\rm fin}}
\def\Rlb{{R_{\rm bound}}}
\def\Rei{{R_{\rm inf}}}
\def \mp {m_{\rm p}}
\def \mpc {m_{\rm p}^{\rm c}}
\def \bp {b_{\rm p}}
\def \cp {c_{\rm p}}
\def \Rc {R_{\rm c}}
\def \pc {p_{\rm c}}
\def \Rcp {R_{\rm c}^{\rm (p)}}
\def \dx {\Delta x}
\def \dv {\Delta v}
\def \Ap {A_{\rm p}}
\def \mH {\mathcal{H}}
\def \Eeff {E_{\rm eff}}
\def \kB {k_{\rm B}}
\def \Ea {E_{\rm a}}
\def \Poincare  {Poincar\'{e}}
\def \ie  {i\/.e\/.}
%\newcommand{\ctext}[3][RGB]{%
%  \begingroup
%  \definecolor{hlcolor}{#1}{#2}\sethlcolor{hlcolor}%
%  \hl{#3}%
%  \endgroup
%}
%\newcommand{\DM}[1]{\ctext[RGB]{128,0,128}{#1}}
\newcommand{\DM}[1]{\colorbox{yellow}{#1}}
\newcommand{\VA}[1]{\colorbox{green}{#1}}
\newcommand{\AD}[1]{\colorbox{red}{#1}}
\newcommand{\ddt}[1]{\tfrac{{\rm d}}{{\rm d}t} #1}
\newcommand{\DDt}[1]{\frac{{\rm D} #1}{{\rm D}t}}
\newcommand{\eq}[1]{~(\ref{#1})}
\newcommand{\Eq}[1]{Eq.~(\ref{#1})}
\newcommand{\fig}[1]{Fig.~(\ref{#1})}
\newcommand{\Fig}[1]{Figure~(\ref{#1})}
\newcommand{\subfig}[2]{Fig.~(\ref{#1}#2)}
\newcommand{\ATT}[1]{\textcolor{red}{#1}}
\newcommand{\NOTE}[1]{\textcolor{blue}{\small{[#1]}}}
\newcommand{\bfig}{\begin{figure}}
\newcommand{\efig}{\end{figure}}
\newcommand{\bc}{\begin{center}}
\newcommand{\ec}{\end{center}}
\newcommand{\bea}{\begin{eqnarray}}
\newcommand{\eea}{\end{eqnarray}}
\def \jfm {Journal of Fluid. Mech.}
\def \an {Astron. Nachr.}
%\def \apj {Astrophys. J.}
\def \apj {ApJ}
%\def \apjl {Astrophys. J. Lett.}
\def \apjl {ApJL}
%\def \mnras {Mon. Not. Roy. Astron. Soc.}
\def \mnras {MNRAS}
\def \pre {Phys. Rev. E}
\def \prl {Phys. Rev. Lett.}
%\def \AandA {Astron. Astrophys.}
\def \AandA {A\&A}
\def \jetp {Sov. Phys. JETP}
\def \solphys {Sol. Phys.}
\def \hamil {\mathcal{H}}
\def \rB {{\rm{B}}}
\def \cA {{\mathcal {A}}}
\def \rH {{\rm H}}
\def \nhat {\hat{{\bm n}}}
\def \cAit {{\mathcal A}^i}
\def \cAib {{\mathcal A}_i}
\def \aij {\alpha_{\rm ij}}
\def \bij {\beta_{\rm ij}}
\def \bijm {\beta_{ij-1}}
\def \zero {{\rm 0}}
\def \out {{\rm out}}
\def \rT {{\rm T}}
\def \LL {{\bm L}}
\def \Sum {\mathlarger{\sum}}
\def \SUM {\mathlarger{\mathlarger{\sum}}}
\def \Esi {\Es^{\rm i}}
\def \RRi {\RR_{\rm i}}
\def \rr {\bm r}
\def \rhat {\hat{\rr}}